set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR mips)

set(OPENWRT_PATH /openwrt)
set(TOOLCHAIN_PATH ${OPENWRT_PATH}/staging_dir/toolchain-mips_24kc_gcc-7.5.0_musl)
set(TOOLCHAIN_PREFIX ${TOOLCHAIN_PATH}/bin/${CMAKE_SYSTEM_PROCESSOR}-openwrt-linux-musl)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)

set(CMAKE_SYSROOT ${OPENWRT_PATH}/staging_dir/target-mips_24kc_musl/)

set(CMAKE_PREFIX_PATH ${CMAKE_SYSROOT}/lib/cmake)

set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
