#!/bin/sh /etc/rc.common
# Copyright (C) 2013 OpenWrt.org

# start after and stop before networking
START=25
STOP=75
PIDCOUNT=0

USE_PROCD=1
PROG=/usr/bin/rsu-connector

start_service()
{
	if [ "x$DPS_IDSCOPE" != "x" ]; then
		sed -ie "s/\"DPS_IDSCOPE\": \"[^\"]*\"/\"DPS_IDSCOPE\": \"$DPS_IDSCOPE\"/" /etc/config/rsu-connector-config.json
	fi

	procd_open_instance
	procd_set_param command "$PROG" /etc/config/rsu-connector-config.json
	procd_set_param respawn 10 -10 -10
	procd_set_param stdout 1 
	procd_set_param stderr 1 
	procd_close_instance
}

